{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gateway.className }}
spec:
  controllerName: io.cilium/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
  - name: http
    port: {{ .Values.gateway.port }}
    protocol: {{ .Values.gateway.protocol }}
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.gateway.routeName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  {{- if .Values.gateway.hostnames }}
  hostnames:
  {{- range .Values.gateway.hostnames }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.gateway.pathPrefix }}
    backendRefs:
    - name: {{ include "chart.fullname" . }}
      port: {{ .Values.service.port }}
      weight: 100
{{- end }}
