{{- if .Values.networkPolicy.enabled -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "chart.fullname" . }}-cilium-policy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  ingress:
  {{- if .Values.gateway.enabled }}
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: cilium-gateway
  {{- end }}
  {{- if .Values.networkPolicy.allowedCIDRs }}
  - fromCIDR:
    {{- range .Values.networkPolicy.allowedCIDRs }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  - ports:
    - port: {{ .Values.containerPort | quote }}
      protocol: TCP
  egress:
  - {}  # Allow all egress traffic
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chart.fullname" . }}-k8s-policy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: {{ .Values.containerPort }}
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: {{ .Values.containerPort }}
  {{- if .Values.networkPolicy.additionalIngressRules }}
  {{- range .Values.networkPolicy.additionalIngressRules }}
  - from:
    {{- if .namespaceSelector }}
    - namespaceSelector:
        {{- toYaml .namespaceSelector | nindent 8 }}
    {{- end }}
    {{- if .podSelector }}
    - podSelector:
        {{- toYaml .podSelector | nindent 8 }}
    {{- end }}
    {{- if .ports }}
    ports:
    {{- range .ports }}
    - protocol: {{ .protocol }}
      port: {{ .port }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
  egress:
  - {}  # Allow all egress
{{- end }}
