{{- if eq .Values.deploymentStrategy "rollout" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-preview
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    service-type: preview
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end }}
